"""
AgentSeal FastAPI Backend Models
--------------------------------

This file defines all request and response schemas for the backend.

Why this is important:
- FastAPI uses these models to validate request data.
- Swagger docs are generated automatically from these models.
- Frontend and backend can follow one predictable data contract.
"""

from typing import List, Literal, Optional

from pydantic import BaseModel, Field


RiskPriority = Literal["Critical", "High", "Medium", "Low"]
RunMode = Literal["before", "after"]
TestStatus = Literal["Passed", "Failed"]
ReviewDecision = Literal["approve", "block", "request_fix", "escalate"]


class AssessmentCreate(BaseModel):
    """
    Payload for creating a new agent assessment.
    """

    agent_name: str = Field(default="Customer Refund Agent")
    domain: str = Field(default="Customer Support / Finance")
    requirement: str = Field(
        default=(
            "This agent helps customers check refund eligibility and create "
            "refund requests. Refunds under $500 can be processed automatically "
            "if the order is valid and within 30 days. Refunds above $500 require "
            "manager approval. Refunds after 30 days must be rejected. The agent "
            "must not reveal customer private data, bypass refund policy, call "
            "refund API before validation, or create duplicate refunds."
        )
    )
    endpoint: Optional[str] = Field(default="mock://refund-agent")
    reviewer_email: Optional[str] = Field(default="reviewer@company.com")


class Assessment(BaseModel):
    """
    Stored assessment object.
    """

    assessment_id: str
    agent_name: str
    domain: str
    requirement: str
    endpoint: Optional[str]
    reviewer_email: Optional[str]
    status: str


class ExtractedPolicy(BaseModel):
    """
    Policy extracted from the submitted requirement.
    """

    assessment_id: str
    business_rules: List[str]
    forbidden_actions: List[str]
    sensitive_data: List[str]
    approval_points: List[str]
    tool_rules: List[str]
    risk_areas: List[str]


class TestCase(BaseModel):
    """
    Test case generated from business rules and safety policies.
    """

    id: str
    category: str
    priority: RiskPriority
    input: str
    expected: str
    risk: str
    risk_points: int


class RedTeamPrompt(BaseModel):
    """
    Adversarial prompt generated by Gladiator Engine.
    """

    id: str
    category: str
    severity: RiskPriority
    attack: str
    expected: str
    risk: str
    risk_points: int


class TestResult(BaseModel):
    """
    One executable test result.
    """

    id: str
    name: str
    category: str
    status: TestStatus
    expected: str
    actual: str
    evidence: str
    failure_type: Optional[str] = None
    risk_points: int = 0


class ExecutionResult(BaseModel):
    """
    Full test execution result.
    """

    assessment_id: str
    run_id: str
    mode: RunMode
    passed: int
    failed: int
    risk_score: int
    decision: str
    results: List[TestResult]


class RiskScore(BaseModel):
    """
    RiskSeal score calculated from failed test results.
    """

    assessment_id: str
    score: int
    level: str
    decision: str
    failed_cases: List[TestResult]
    explanation: str


class HumanReviewRequest(BaseModel):
    """
    Human reviewer decision payload.
    """

    decision: ReviewDecision
    reviewer: str = Field(default="Maya Rahman")
    note: str = Field(
        default="Reviewed evidence and approved after risk reduction."
    )


class MonitoringLog(BaseModel):
    """
    Runtime monitoring log.
    """

    id: str
    user_input: str
    agent_response: str


class MonitoringReplayRequest(BaseModel):
    """
    Payload for replaying runtime logs and detecting new risks.
    """

    logs: List[MonitoringLog]


    